export const assetIdMap: Record<string, string> = {
  // Cryptos
  btc:    "Bitcoin",
  eth:    "Ethereum",
  sol:    "Solana",
  bnb:    "Binance Coin",
  ada:    "Cardano",
  dot:    "Polkadot",
  doge:   "Dogecoin",
  ripple: "Ripple",
  bitcoin:    "Bitcoin",
  ethereum:   "Ethereum",
  solana:     "Solana",
  binancecoin:"Binance Coin",
  cardano:    "Cardano",
  polkadot:   "Polkadot",
  dogecoin:   "Dogecoin",

  // Major Stocks
  AAPL:  "Apple",
  MSFT:  "Microsoft",
  GOOGL: "Google",
  AMZN:  "Amazon",
  TSLA:  "Tesla",
  NVDA:  "NVIDIA",
  META:  "Meta Platforms",
  "BRK.B":"Berkshire Hathaway",
  TSM:   "Taiwan Semiconductor Manufacturing Company",
  V:     "Visa",
  JNJ:   "Johnson & Johnson",
  WMT:   "Walmart",
  MA:    "Mastercard",
  JPM:   "JPMorgan Chase",
  PG:    "Procter & Gamble",
  UNH:   "UnitedHealth Group",
  HD:    "Home Depot",
  DIS:   "The Walt Disney Company",
  ADBE:  "Adobe",
  PYPL:  "PayPal",
  NFLX:  "Netflix",
  KO:    "Coca-Cola",
  PEP:   "PepsiCo",
  XOM:   "Exxon Mobil",
  CVX:   "Chevron",
  INTC:  "Intel",
  CSCO:  "Cisco Systems",
  CRM:   "Salesforce",
  ORCL:  "Oracle",
  PFE:   "Pfizer",
  MRK:   "Merck",
  ABT:   "Abbott Laboratories",
  TMO:   "Thermo Fisher Scientific",
  ASML:  "ASML Holding",
  AVGO:  "Broadcom",
  MCD:   "McDonald's",
  NKE:   "Nike",
  LLY:   "Eli Lilly",
  TXN:   "Texas Instruments",
  COST:  "Costco Wholesale",
  BAC:   "Bank of America",
  C:     "Citigroup",
  WFC:   "Wells Fargo",
  GS:    "Goldman Sachs",
  MS:    "Morgan Stanley",
  UPS:   "United Parcel Service",
  NEE:   "NextEra Energy",
  DHR:   "Danaher",
  BMY:   "Bristol-Myers Squibb",
  HON:   "Honeywell",

  // Major ETFs
  SPY: "SPDR S&P 500 ETF Trust",
  QQQ: "Invesco QQQ Trust",
  VTI: "Vanguard Total Stock Market ETF",
  IWM: "iShares Russell 2000 ETF",
  EEM: "iShares MSCI Emerging Markets ETF",
  EFA: "iShares MSCI EAFE ETF",
  AGG: "iShares Core U.S. Aggregate Bond ETF",
  LQD: "iShares iBoxx $ Investment Grade Corporate Bond ETF",
  HYG: "iShares iBoxx $ High Yield Corporate Bond ETF",
  VNQ: "Vanguard Real Estate ETF",
  XLF: "Financial Select Sector SPDR Fund",
  XLY: "Consumer Discretionary Select Sector SPDR Fund",
  XLP: "Consumer Staples Select Sector SPDR Fund",
  XLV: "Health Care Select Sector SPDR Fund",
  XLI: "Industrial Select Sector SPDR Fund",
  XLE: "Energy Select Sector SPDR Fund",
  XLK: "Technology Select Sector SPDR Fund",
  XLB: "Materials Select Sector SPDR Fund",
  XLC: "Communication Services Select Sector SPDR Fund",
  GLD: "SPDR Gold Shares",
  "XWD.TO": "iShares MSCI World UCITS ETF (Acc)",   // akkumulierend :contentReference[oaicite:2]{index=2}
  "XDWL.DE": "iShares MSCI World UCITS ETF (Dist)"   // ausschüttend :contentReference[oaicite:3]{index=3}
};